on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE1: "ghcr.io/${{ github.repository }}:latest"
      IMAGE2: "ghcr.io/${{ github.repository }}:1.0"
      SIZE: $((1*1024))

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE1 }} --tag ${{ env.IMAGE2 }} --build-arg SIZE=${{ env.SIZE }}

    - run: docker login https://ghcr.io -u token --password-stdin <<< ${{ secrets.WRITE_PACKAGES_TOKEN }}
    - name: Push the image
      run: |
        docker push ${{ env.IMAGE1 }} &
        docker push ${{ env.IMAGE2 }} &
        wait
