on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE: ghcr.io/${{ github.repository }}/docker-large-images-test
      SIZE: $((4*1024*1024))

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE }} --build-arg SIZE=${{ env.SIZE }}

    - run: docker login https://ghcr.io -u token -p ${{ secrets.WRITE_PACKAGES_TOKEN }}
    - name: Push the image
      run: docker push ${{ env.IMAGE }}
